// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxqeazglzjvdsfwklbap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4cWVhemdsemp2ZHNmd2tsYmFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NzY2OTAsImV4cCI6MjA3MTQ1MjY5MH0.h5_CNuJbEsYIFsv0rznjouUZxFZhAdZTUScbaskbXE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});